format_version: 10
pipelines:
  test-job:
    materials:
      deploy:
        git: https://github.com/vijayavanisabbiti/expense-ansible
        shallow_clone: false
        auto_update: true
        branch: main

    stages:
      - dev:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          jobs:
            deploy:
              timeout: 0
              tasks:
                - exec:
                    command: echo Deploying to Dev env
                    run_if: passed

      - qa:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          jobs:
            deploy:
              timeout: 0
              tasks:
                - exec:
                    command: echo Deploying to QA env
                    run_if: passed

      - uat:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          jobs:
            deploy:
              timeout: 0
              tasks:
                - exec:
                    command: echo Deploying to UAT env
                    run_if: passed

      - prod:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          jobs:
            deploy:
              timeout: 0
              tasks:
                - exec:
                    command: echo Deploying to Prod env
                    run_if: passed

