format_version: 10
pipelines:
  MutableDeployment_Backend:
    group: defaultGroup
    environment_variables:
      APP_VERSION: ""
    materials:
      deploy:
        git: https://github.com/vijayavanisabbiti/expense-ansible
        shallow_clone: true
        auto_update: false
        branch: main

    stages:
      - dev:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          environment_variables:
            ENV: dev
            approval:
              type: manual
          jobs:
            deploy:
              timeout: 0
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "Deploying to Dev env"
                    run_if: passed

      - qa:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            deploy:
              timeout: 0
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "Deploying to QA env"
                    run_if: passed

      - uat:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            deploy:
              timeout: 0
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "Deploying to UAT env"
                    run_if: passed

      - prod:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          environment_variables:
            ENV: prod
            approval:
              type: manual
          jobs:
            deploy:
              timeout: 0
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "Deploying to Prod env"
                    run_if: passed


